name: test

on:
  push: 
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install || exit 1

      - name: Run tests
        run: |
          echo "Running tests..."
          npm run test || exit 1
      